name: R-CMD

# Controls when the action will run. 
on: [push, pull_request]

jobs:
  R-CMD:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false 
      matrix:
        config:
          # for latest stable version of R for MacOSX
          - {os: macOS-latest, r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: false #? 
      GCAMDATA_USE_JAVA: TRUE #??

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"), repos = "https://cloud.r-project.org")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      
      - name: Check
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--ignore-vignettes", "--no-build-vignettes"), error_on = "error", check_dir = "check")
        shell: Rscript {0}